// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trashury.Data;

#nullable disable

namespace Trashury.Data.Migrations
{
    [DbContext(typeof(TrashuryDbContext))]
    [Migration("20260921090656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Trashury.Models.DetailSetoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BeratKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetoranSampahId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("SetoranSampahId");

                    b.ToTable("DetailSetoran");
                });

            modelBuilder.Entity("Trashury.Models.KategoriSampah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FaktorEmisiCO2e")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HargaPerKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nama")
                        .IsUnique();

                    b.ToTable("KategoriSampah");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FaktorEmisiCO2e = 1.5m,
                            HargaPerKg = 4000m,
                            Nama = "Plastik PET"
                        },
                        new
                        {
                            Id = 2,
                            FaktorEmisiCO2e = 0.9m,
                            HargaPerKg = 2000m,
                            Nama = "Kertas & Kardus"
                        },
                        new
                        {
                            Id = 3,
                            FaktorEmisiCO2e = 8.1m,
                            HargaPerKg = 15000m,
                            Nama = "Kaleng Aluminium"
                        },
                        new
                        {
                            Id = 4,
                            FaktorEmisiCO2e = 0.3m,
                            HargaPerKg = 500m,
                            Nama = "Kaca"
                        },
                        new
                        {
                            Id = 5,
                            FaktorEmisiCO2e = 0.25m,
                            HargaPerKg = 300m,
                            Nama = "Organik"
                        });
                });

            modelBuilder.Entity("Trashury.Models.Nasabah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT")
                        .HasColumnName("Saldo");

                    b.HasKey("Id");

                    b.ToTable("Nasabah");
                });

            modelBuilder.Entity("Trashury.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JenisTransaksi")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("NasabahId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Nominal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NasabahId");

                    b.HasIndex("Tanggal");

                    b.ToTable("Transaksi");

                    b.HasDiscriminator<string>("JenisTransaksi").HasValue("Transaksi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Trashury.Models.PenarikanSaldo", b =>
                {
                    b.HasBaseType("Trashury.Models.Transaksi");

                    b.Property<decimal>("JumlahTarik")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Penarikan");
                });

            modelBuilder.Entity("Trashury.Models.SetoranSampah", b =>
                {
                    b.HasBaseType("Trashury.Models.Transaksi");

                    b.HasDiscriminator().HasValue("Setoran");
                });

            modelBuilder.Entity("Trashury.Models.DetailSetoran", b =>
                {
                    b.HasOne("Trashury.Models.KategoriSampah", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trashury.Models.SetoranSampah", null)
                        .WithMany("DetailSetoran")
                        .HasForeignKey("SetoranSampahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Trashury.Models.Transaksi", b =>
                {
                    b.HasOne("Trashury.Models.Nasabah", null)
                        .WithMany()
                        .HasForeignKey("NasabahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trashury.Models.SetoranSampah", b =>
                {
                    b.Navigation("DetailSetoran");
                });
#pragma warning restore 612, 618
        }
    }
}
